auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# Limit configuration
limits_config:
  # Increase from default 4MB to handle larger log entries
  max_entries_limit_per_query: 5000
  # Per-stream rate limit (default is 4MB)
  ingestion_rate_mb: 8
  # Burst size for ingestion
  ingestion_burst_size_mb: 16
  # Max query length
  max_query_length: 721h
  # Retention period
  retention_period: 168h

# Table manager for retention
table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

# Compactor for managing retention
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
