server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Scrape logs from all Docker containers
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Use container name as job
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'job'
      # Extract service name
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.+)'
        target_label: 'container'
      # Add docker image label
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      # Add container ID
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
    pipeline_stages:
      # Parse JSON logs if available
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
      # Extract log level
      - labels:
          level:
      # Add timestamp
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      # Output stage for debugging
      - output:
          source: message

  # Scrape user-service logs
  - job_name: user-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: user-service
          service: user-service
          __path__: /var/log/user-service/*.log

  # Scrape product-service logs
  - job_name: product-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: product-service
          service: product-service
          __path__: /var/log/product-service/*.log

  # Scrape order-service logs
  - job_name: order-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: order-service
          service: order-service
          __path__: /var/log/order-service/*.log

  # Scrape notification-service logs
  - job_name: notification-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: notification-service
          service: notification-service
          __path__: /var/log/notification-service/*.log
